#ifndef _C64UCONNECTIONSTATUS_H_
#define _C64UCONNECTIONSTATUS_H_

enum EC64UConnectionStatus
{
	C64U_CONNECTION_STATUS_DISCONNECTED = 0,
	C64U_CONNECTION_STATUS_CONNECTING,
	C64U_CONNECTION_STATUS_AUTHENTICATING,
	C64U_CONNECTION_STATUS_CONNECTED,
	C64U_CONNECTION_STATUS_STREAMING,
	C64U_CONNECTION_STATUS_RECONNECTING,
};

#endif
